config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users
            #  :path => '',
            #  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :bookings, only: [:create]
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :summary, presence: true, length: {maximum: 500}
  validates :address, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #confirmable

  validates :fullname, presence: true, length: {maximum: 50}

  has_many :rooms
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_paramaters, if: :devise_controller?

  protected
  def configure_permitted_paramaters
    devise_parameter_sanitizer.for(:sign_up) << :fullname
    devise_parameter_sanitizer.for(:account_update) << :fullname
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @booking = current_user.bookings.create(booking_params)

    redirect_to @booking.room, notice: "You booking has been created"
  end

  private
    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :price, :total, :room_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save

      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end

      @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Saved!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You do not have permission to do this!"
    end
  end

  def update
    if @room.update(room_params)

      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end

      redirect_to edit_room_path(@room), notice: "Updated"
    else
      render :edit
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:image, :home_type, :room_type, :accomodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_wifi, :is_aircon, :is_heating, :price, :active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identitcal&s=150}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/Photos/_list.html.erb
<% if @photos %>
  <div class="row">
    <% @photos.each do |photo|  %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url(:thumb) %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <i class="fa fa-times fa-lg"></i>
            </span>
          </div>
        </div>
      </div>
      <% end %>
  </div>

  <% end %>

app/views/bookings/_form.html.erb
<%= form_for([@room, @room.bookings.new]) do |f| %>

  <div class="row">
    <div class="col-md-6">
      <label>Check In</label>
      <%= f.text_field :start_date, readonly: 'true', placeholder: 'Start Date' %>
    </div>
    <div class="col-md-6">
      <label>Check Out</label>
      <%= f.text_field :end_date, readonly: 'true', placeholder: "End Date", disabled: 'true' %>
    </div>
  </div>

  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :price, value: @room.price %>
  <%= f.hidden_field :total, id: 'booking_total' %>

  <div id="preview" style="display:none">
    <h4><span id="message"></span></h4>

    <table class="booking-table">
      <tbody>
        <tr>
          <td>Day(s)</td>
          <td><span id="booking_days"></span></td>
        </tr>
        <tr>
          <td>Total</td>
          <td><span id="booking_sum"></span></td>
        </tr>
      </tbody>
    </table>
  </div>

  <br>
  <%= f.submit "Book Now", class: "btn pink" %>
<% end %>

<script>
  $(function() {
    $('#booking_start_date').datepicker({
      dateFormat: "dd-mm-yy"
    });
    $('#booking_end_date').datepicker({
      dateFormat: "dd-mm-yy"
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FlatFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'partials/navbar' %>

  <%=  render 'partials/message' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to</h1>
<%= image_tag("Logo.png")%>
  <h4>
    Having a hard time finding a quick easy solution for renting a flat, on a short hold basis?
  </h4>
    <p>Then let's get started!
      If you're a first time user, please <%= link_to "Sign up", new_user_registration_path %> for a free account today.
    </p>
    <p>Or if you're already registered </p>
    <p>please look at <%= link_to "available", rooms_path %> rooms, or if you are a host <%= link_to "create", new_room_path %> a room.</p>

app/views/partials/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>

<% end %>

app/views/partials/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1]%>')
    <% end %>
  </script>
<% end %>

<!-- flash[:notice] = "Email is not correct" -->

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- <a class="navbar-brand" href="#" id="logo"><%= link_to 'FlatFinder', root_path, :id => "logo" %></a> -->
            <a class="navbar-brand" href="#" id="logo"><%= link_to(image_tag("Logo.png"), root_path, :id => "img-logo")%></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

              <% if(!user_signed_in?) %>
                <li><%= link_to "Log In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                aria-expanded="false">
                <%= image_tag avatar_url(current_user), class: "img-circle avatar-small"%>&nbsp;
                <%= current_user.fullname %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Your Trips</a></li>
                  <li><a href="#">Wish List</a></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Account Settings</a></li>
                  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
              <% end %>

              <li>
                <a href=""><i class="fa fa-envelope-o nav-con">&nbsp;Messages</i></a>
              </li>
              <li>
                <a href=""><i class="fa fa-home nav-con">&nbsp;Become a host</i></a>
              </li>
            </ul>
          </div><!--/.nav-collapse end -->
        </div><!--/.container-fluid end-->
      </nav>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your place
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @room, html: { multipart: true } do |f| %>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Appartment", "Appartment"], ["House", "House"],["Bnb", "Bnb"]],
                          id: "home_type", prompt: "Select", class: "form-control" %>
            </div>
          </div>


          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"],
                          ["Shared", "Shared"]], prompt: "Select",class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accomodate</label>
              <%= f.select :accomodate, [["1", "1"],["2", "2"],["3", "3"],["4", "4"],
                            ["5", "5"],["6+", "6"]] ,prompt: "Select", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [["1", "1"],["2", "2"],["3", "3"],["4+", "4"]],
                            prompt: "Select", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [["1", "1"],["2", "2"],["3", "3"],["4+", "4"]],
                            prompt: "Select", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
            <div class="form-group">
              <label>Listing name</label>
              <%= f.text_field :listing_name, placeholder: "Be clear and descriptive", class: "form-control" %>
            </div>
        </div>

        <div class="row">
            <div class="form-group">
              <label>Summary</label>
              <%= f.text_area :summary, rows: 5,  placeholder: "Tell us about your property", class: "form-control" %>
            </div>
        </div>

        <div class="row">
            <div class="form-group">
              <label>Address</label>
              <%= f.text_field :address, placeholder: "What is your address?", class: "form-control" %>
            </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="form-group">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="form-group">
              <%= f.check_box :is_wifi %> Wifi
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="form-group">
              <%= f.check_box :is_aircon %> Air Conditioning
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Price p/night</label>
              <div class="input-group">
                <div class="input-group-addon">£</div>
                <%= f.text_field :price, placeholder: "£120", class: "form-control" %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <span class="btn-default btn-file">
                <i class="fa fa-cloud-upload fa-lg">Upload Photos</i>
                <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>
            </div>
          </div>
        </div>

        <div id="photos"><%= render 'photos/list' %></div>

        <div class="row">
          <div class="form-group">
            <%= f.check_box :active %> Active
          </div>
        </div>

        <div class="actions">
          <%= f.submit "Save", class: 'btn pink' %>
        </div>


        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/_map.html.erb
<div id="map"></div>

<style>
  #map {
    width: 100%;
    height: 400px;
  }
</style>

<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
    var mapCanvas = document.getElementById('map');
    var mapOptions = {
          center: new google.maps.LatLng(<%= @room.latitude %>, <%= @room.longitude %>),
          zoom: 15,
          //mapTypeId: google.maps.MapTypeId.ROADMAP
          mapTypeId: google.maps.MapTypeId.HYBRID
          //mapTypeId: google.maps.MapTypeId.TERRAIN
    }
    var map = new google.maps.Map(mapCanvas, mapOptions);

    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(<%= @room.latitude %>, <%= @room.longitude %>),
      title: "FlatFider"
    });

    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class: "sidebar-link active" %></li>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">
        <%  @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <%=  image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %>
            </div>
            <div class="col-md-7">
              <h4><%= room.listing_name %></h4>
            </div>
            <div class="col-md-3">
              <%= link_to "Update", edit_room_path(room), class: "btn pink" %>
            </div>
          </div>
          <hr>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <!-- Image -->
    <div class="row">
      <div class="col-md-12">
        <%= image_tag @photos[0].image.url(), class: "image-responsive" %>
      </div>
    </div>

    <br>
    <!-- Info -->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 tex-center">
            <%=  image_tag avatar_url(@room.user), class: "img-circle avatar-large" %>
            <br>
            <%= @room.user.fullname %>
          </div>

          <div class="col-md-9">
          <h4><%= @room.listing_name %></h4>
          <%= @room.address %>

          <div class="row text-center row-space-1">
            <div class="col-sm-3">
              <i class="fa fa-home fa-2x"></i>
            </div>
            <div class="col-sm-3">
              <i class="fa fa-users fa-2x"></i>
            </div>
            <div class="col-sm-3">
              <i class="fa fa-bed fa-2x"></i>
            </div>
            <div class="col-sm-3">
              <i class="fa fa-tint fa-2x"></i>
            </div>
          </div>

          <div class="row text-center">
            <div class="col-sm-3">
              <%= @room.home_type %>
            </div>
            <div class="col-sm-3">
              <%= pluralize(@room.accomodate, "Guest") %>
            </div>
            <div class="col-sm-3">
                <%= pluralize(@room.bed_room, "Bathroom") %>
            </div>
            <div class="col-sm-3">
                <%= pluralize(@room.bath_room, "Bedroom") %>
            </div>
          </div>
        </div>
      </div>
      </div>

      <div class="col-md-4">
        <!-- Booking form -->
        <%= render 'bookings/form' %>
      </div>
    </div>


    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h2>About this property</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-2">
        <p>Amenities</p>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%='text-line-through'if @room.is_tv%>">TV</li>
              <li class="<%='text-line-through'if @room.is_kitchen%>">Kitchen</li>
              <li class="<%='text-line-through'if @room.is_wifi%>">Wifi</li>
              </ul>
          </div>
            <ul class="amenities">
            <div class="col-md-6">
              <li class="<%='text-line-through'if @room.is_heating%>">Heating</li>
              <li class="<%='text-line-through'if @room.is_aircon%>">Air Conditioning</li>
            </ul>
            </div>
        </div>
      </div>
    </div>

    <hr>
    <!-- Maps -->
    <div class="row">
      <div class="col-md-12">
        <%= render 'rooms/map' %>
      </div>
    </div>

    <!-- Close by Rooms -->
    <h3>Properties near you</h3>
    <div class="row">
      <% for room in @room.nearbys(10) %>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag room.photos[0].image.url(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room %><br/>
              (<%= room.distance.round(2) %> Miles away)
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="center">
      <%= image_tag avatar_url(@user), class: "img-circle avatar-full"%>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Verification</div>
      <div class="panel-body">
        Email Address <br>
        Phone Number
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>

    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>